### ISSUE TITLE
The dataset properties should be editable by the user

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#55] opened 2023-03-14 09:12 UTC
The payload request to the server shall include only the property of the dataset to be updated.

Eg. Payload request to update dataset name

```
{
  "name": "Something"
}
```

There is a reference to an issue currently open server-side 
- https://github.com/fractal-analytics-platform/fractal-common/issues/31

**Comment by tcompa** [comment] 2023-03-14 16:03
We reviewed https://github.com/fractal-analytics-platform/fractal-common/issues/31 with @ychiucco, and it looks like it is already correct in the latest fractal-server version (i.e. `1.1.0a1`).

We only found some minor issues, which are fixed and will be released with the next version (`1.1.0`, coming soon..), but they should not affect development of the web client in principle.

**Comment by tcompa** [comment] 2023-03-16 07:59
As of #51, the recent versions of fractal-server (I'm testing with `1.1.0a3`) perform some more strict validation of request bodies. In many cases, we do not accept that an optional field is set to `None` or to an empty string. The expected behavior for fractal-web is that it removes the empty-string attributes from request bodies.

It seems that the current version of the dataset-edit feature still sends payloads with empty-string attributes. For instance if I only set the new `Dataset name` attribute, the error message reads
```
There has been an error, reason:

{
  "reason": {
    "detail": [
      {
        "loc": [
          "body",
          "type"
        ],
        "msg": "String attribute 'type' cannot be empty",
        "type": "value_error"
      }
    ]
  }
}
```

**Closed** 2023-04-03 09:50 UTC

**Comment by rkpasia** [comment] 2023-04-03 10:41
Be aware that it will not be possible to "reset" the property `type` of the dataset to an empty state as it is when created.
