### ISSUE TITLE
Optimize page loading times in real-world deployments

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#361] opened 2023-12-04 13:54 UTC
Having deployed Fractal web 0.7.0 at UZH: The new spinner during loading of pages shows up quite often. I think it loads them about as fast as before, but it makes it a bit more obvious how one is waiting for page loads much more in the real deployments than when running on the local machine directly.
Here is an example video of where it comes up: https://drive.google.com/file/d/183UKvgyRrBsBPzKpzIltzcJJB02M_kR1/view?usp=sharing

Some interesting things to test:
1. If we use the full UZH db and run locally, how is performance then? [is Fractal server or Fractal web itself the limit for larger dbs?]
2. If we run without the Apache proxy server (e.g. by just port-forwarding the Fractal web port), how is the performance? [Is the proxy a limiting factor?]
3. Which separate Fractal server calls are necessary vs. what could be combined. This was also the motivation for this issue here: https://github.com/fractal-analytics-platform/fractal-web/issues/359

**Comment by zonia3000** [comment] 2023-12-05 08:24
Currently the spinner has a delay of 250ms and can be easily customized, however I would keep it lower than 500ms.

**Comment by jluethi** [comment] 2023-12-05 11:51
Could you point me to how I can adjust it? So that I could experiment a bit with it :)

**Comment by zonia3000** [comment] 2023-12-05 13:10
Sure, it's this `transition-delay` CSS property in `src/routes/+layout.svelte`:

https://github.com/fractal-analytics-platform/fractal-web/blob/85388fe956f0f261b4db41a7a7d43143c91a64a3/src/routes/%2Blayout.svelte#L146

**Comment by tcompa** [comment] 2023-12-06 14:57
Reference database (up-to-date with fractal-server 1.4.0):
https://github.com/fractal-analytics-platform/fractal-server/blob/main/tests/data/migration_1.3_to_1.4/clean_db_fractal_1.4.0a6.sql

**Comment by jluethi** [comment] 2023-12-14 12:15
I was just working with a few users at FMI and noticed the following:
Users with very few Fractal projects, jobs etc. had a very smooth experience. Users that had ran many jobs and have many projects have much longer loading times.

I then tested this on my laptop by logging in as different users. The more they've already used it, the more the spinner comes up & the longer the waiting time. For users with only e.g. 1 project and 2 jobs, everything loads very smoothly

=> There is clearly a scaling issue here, because performance is fine for users with few entries in the db.

**Comment by tcompa** [comment] 2023-12-15 07:57
During profiling, let's report any possible backend bottleneck e.g. at https://github.com/fractal-analytics-platform/fractal-server/issues/1089.

**Comment by zonia3000** [comment] 2023-12-15 09:59
I'm doing some tests using the realistic database on the projects page. I'm not able to reproduce the very slow timing shown in the video, however the page loads in around 600ms, that is a lot considering it has only to display a simple table with less than 60 items.

Currently the project page loads all the projects (`/project/` - 180ms) and all the datasets (`/dataset/` - 230ms). The dataset endpoint payload is also quite big (1.3 MB). The datasets are needed only to display them inside the info modals, so we can also decide to load them only when the user opens those modals, reducing most of the time spent in performing API calls. Moreover, in that case we can call the project specific endpoint, that is faster (`/project/{id}/dataset/` - 130ms).

To exclude the possibility that our Svelte proxy has an impact on the loading time, I've registered the time both calling fractal-web and calling fractal-server and I obtained similar results. In a production environment, where fractal-web and fractal-server are deployed on different machines, we have to consider also some overhead for that, simply due to the network, but I assume that it would be a constant time (except for very large payloads, that it's not the current case).

Another constant overhead are the calls to the `/auth/current-user/` endpoint, that are done at each page load. I would store this information inside a cookie that has to be destroyed when the auth cookie expires or is deleted.

**Comment by jluethi** [comment] 2023-12-15 10:58
@tcompa Could you share the current UZH database with Sonia for testing. To compare performance e.g. between my user & Adrian's user and e.g. the user Ruth (who has far fewer jobs in the db, fewer projects etc.

**Comment by tcompa** [comment] 2023-12-15 11:00
> @tcompa Could you share the current UZH database with Sonia for testing.

This is the DB she's using for the tests above, if I'm not mistaken (updated at a couple of days ago).

**Comment by jluethi** [comment] 2023-12-15 11:03
If that's the db, would be interesting to get local performance measurements for users with few vs. many projects, datasets, jobs etc.

**Comment by tcompa** [comment] 2023-12-15 13:44
> > @tcompa Could you share the current UZH database with Sonia for testing.
> 
> This is the DB she's using for the tests above, if I'm not mistaken (updated at a couple of days ago).

There was probably some confusion between the anonymized and original version, we are re-running the checks.

**Comment by tcompa** [comment] 2023-12-15 13:51
After using a more realistic DB, the projects page has these timings:

loading time: 1.7 s
API call to `GET /api/v1/projects/`: 550 ms
API call to `GET /api/v1/datasets/`: 670 ms
API call to `GET /auth/current-user/`: 308 ms

Same API calls with curl
API call to `GET /api/v1/projects/`: 524 ms
API call to `GET /api/v1/datasets/`: 686 ms
API call to `GET /auth/current-user/`: 291 ms


Take-home message: fractal-web is doing just fine, slowdowns must be investigated backend-side.

**Comment by tcompa** [comment] 2023-12-15 13:54
For the record: removing the CORS-related middleware seems to have a negligible effect.

**Comment by jluethi** [comment] 2023-12-15 14:57
That's great to know! Thanks for the numbers!

**Comment by tcompa** [comment] 2023-12-15 15:04
> Take-home message: fractal-web is doing just fine, slowdowns must be investigated backend-side.

This is being handled in https://github.com/fractal-analytics-platform/fractal-server/pull/1091. Let's see if we hit any blocker.

**Comment by tcompa** [comment] 2023-12-18 10:12
This issue is now fixed with fractal-server 1.4.1 (identical to 1.4.1a2).
We can still make an additional improvement, now deferred to #377

**Closed by tcompa** 2023-12-18 10:12 UTC
Labels: performance

**Comment by jluethi** [comment] 2023-12-18 10:15
Just to confirm: With fractal server 1.4.1 on the UZH & FMI deployment, performance has improved drastically! :)

Nice if we find additional ways to improve & ensure it remains scalable. But it feels much better again to browse Fractal web for users with many projects now
