### ISSUE TITLE
`enum` support within `definitions`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#503] opened 2024-05-31 08:29 UTC
I have two JSON Schemas, both making use of `definitions`

The first one
```json
{
  "title": "TaskFunction1",
  "type": "object",
  "properties": {
    "arg1": {
      "$ref": "#/definitions/InitArgsRegistration",
      "title": "Arg1",
      "description": "Description of arg1."
    }
  },
  "required": [
    "arg1"
  ],
  "additionalProperties": false,
  "definitions": {
    "InitArgsRegistration": {
      "title": "InitArgsRegistration",
      "description": "Registration init args.",
      "type": "object",
      "properties": {
        "reference_zarr_url": {
          "title": "Reference Zarr Url",
          "type": "string"
        }
      },
      "required": [
        "reference_zarr_url"
      ]
    }
  }
}
```
renders correctly in the sandbox
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/eb477b76-3251-4f74-af91-2c0c3e5ad6c2)

---

The second one
```json
{
  "title": "TaskFunction2",
  "type": "object",
  "properties": {
    "arg2": {
      "$ref": "#/definitions/Color",
      "title": "Arg2",
      "description": "Description of arg2."
    }
  },
  "required": [
    "arg2"
  ],
  "additionalProperties": false,
  "definitions": {
    "Color": {
      "title": "Color",
      "description": "An enumeration.",
      "enum": [
        1,
        2
      ]
    }
  }
}
```
does not render:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/2e00aeed-49fd-4d28-8283-499f46d0fbcc)
and dev-tools log do not show anything special
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/356e8ac0-e1cc-4fe4-a01e-f764ed564dc4)

---

As a double check, the second schema does render on https://rjsf-team.github.io/react-jsonschema-form/:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/defd0058-6412-4457-aa10-3791cab967d8)

---

What is that makes our current form creation fail?
Is it because in the second one the definition of `Color` does not have an additional nested `properties` property?

**Comment by zonia3000** [comment] 2024-06-06 09:23
This will be fixed with the next PR.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/d6c8ce43-a997-4c81-b726-3dbfc6e52c17)

Just a quick note: the problem was not caused by the fact that the enum is within definitions, but that it is missing the `type` field (that should not be mandatory since one can have enums with multiple types in it) and we were not handling that case.

**Comment by tcompa** [comment] 2024-06-07 08:50
> This will be fixed with the next PR.

Great!

For the record, starting from the next version (> 1.0.2), `fractal-tasks-core` will support generating this kind of JSON Schemas with `enum`s (and I already tested that they play well with the new `json-schema` branch of fractal-web, see details in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/745).

Thus let's make sure that we also update the `fractal-web` version before someone starts using these new schemas.

**Closed** 2024-06-12 10:23 UTC
Labels: JSON Schemas
