### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by alexschroeter** [fractal-analytics-platform/fractal-web#329] opened 2023-11-07 15:45 UTC
Created a test workflow.

Browser is Firefox 

Request: 
{"args":{"num_levels":5,"coarsening_xy":2,"image_extension":"tif","overwrite":false,"allowed_channels":[{"wavelength_id":"A01_C01","label":"DAPI","window":{"start":110,"end":800},"active":true,"coefficient":1,"inverted":false},{"wavelength_id":"A02_C03","label":"Lamin B1","window":{"start":110,"end":1600},"active":true,"coefficient":1,"inverted":false}]}}

Response:
405 PATCH method not allowed

Referer:
http://localhost:5173/projects/1/workflows/1

Console Output of a Test deployment

In updateFormEntry, requestData is {"args":{"num_levels":5,"coarsening_xy":2,"image_extension":"tif","overwrite":false,"allowed_channels":[{"wavelength_id":"A01_C01","label":"DAPI","window":{"start":110,"end":800},"active":true,"coefficient":1,"inverted":false},{"wavelength_id":"A02_C03","label":"Lamin B1","window":{"start":110,"end":1600},"active":true,"coefficient":1,"inverted":false}]}} [task_form_utils.js:25:10](http://localhost:5173/src/lib/components/workflow/task_form_utils.js)
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [JSchema.svelte:123:28](http://localhost:5173/src/lib/components/common/jschema/JSchema.svelte)
    saveChanges JSchema.svelte:123

In updateFormEntry, requestData is {"args":{"num_levels":5,"coarsening_xy":2,"image_extension":"tif","overwrite":false,"allowed_channels":[{"wavelength_id":"A01_C01","label":"DAPI","window":{"start":110,"end":800},"active":true,"coefficient":1,"inverted":false},{"wavelength_id":"A02_C03","label":"Lamin B1","window":{"start":110,"end":1600},"active":true,"coefficient":1,"inverted":false}]}} [task_form_utils.js:25:10](http://localhost:5173/src/lib/components/workflow/task_form_utils.js)
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [JSchema.svelte:123:28](http://localhost:5173/src/lib/components/common/jschema/JSchema.svelte)
    saveChanges JSchema.svelte:123

<img width="406" alt="Screenshot 2023-11-07 164832" src="https://github.com/fractal-analytics-platform/fractal-web/assets/57448573/3ab1f590-28a1-45ec-a05d-27e9169e7a1b">

**Comment by tcompa** [comment] 2023-11-07 15:48
Thanks a lot for reporting!

We are somehow trying to PATCH the `/auth/login` endpoint, which seems wrong.

**Comment by zonia3000** [comment] 2023-11-13 14:27
The bug can be reproduced deleting the cookie before executing a `PATCH` request. 
The attempt of executing a `PATCH` request to the `/auth/login` endpoint was caused by an incorrect handling of session expiration for AJAX requests. This will be fixed by fa90362c59e8b96e1d0d75558d724a2403612e52, PR #333. In these cases the user will be redirected to the login page with a proper "session expired" message.

**Closed** 2023-11-14 08:34 UTC
Labels: bug
